services:
  backend:
    restart: unless-stopped
    build:
      context: ./backend  
    volumes:
      - ./backend/src/database.db:/app/database.db
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
    depends_on:
      - backend
    volumes:
      - ./frontend/public:/app/public
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_URL_API=http://18.118.23.134:3001