version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/src/database.db:/app/database.db
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    volumes:
      - ./frontend/public:/app/public
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_URL_API="http://3.133.116.145"


